name: "Style check"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^11.0" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: phpcs
        run: composer run phpcs

      - name: phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: phpmd
        run: composer run phpmd
